

TABLE_MAPPINGS:

  t3_oud:
    sas_ds: state_elgblty_grp_sud
    sheet_num_op: D.3.
    use_class: TableClassWideTransform
    use_sud_ds:
      - state_sud_methods
    group_cols: 
      - elgblty_grp_cat
    denom: count
    numer: count
    numer_col: pop_sud
    numer_value: ==1
    group_order: 
      - 1
      - 2
      - 3
      - 4
      - 5
      - 0
    big_denom:
      - pop_tot_base
    excel_order:
      - big_denom
      - denom
      - count
      - stat