# config for sud db tables

TABLE_MAPPINGS:
# config for sud db tables

TABLE_MAPPINGS:
  t1:
    sas_ds: state_sud_methods
    sheet_num: A.1.
    numerators: 
      - pop_sud_tot
      - pop_sud_alchl_tot 
      - pop_sud_cnnbs_tot 
      - pop_sud_opioids_tot 
      - pop_sud_plysbstnce_tot 
      - pop_sud_stmlnts_tot 
      - pop_sud_tbcco_tot 
      - pop_sud_other_tot 
    big_denom:
      - pop_tot_base
    excel_order:
      - big_denom
      - count
      - pct

  t2:
    sas_ds: state_sud_methods
    sheet_num: A.2.
    numerators: 
      - pop_sud_alchl_tot 
      - pop_sud_cnnbs_tot 
      - pop_sud_opioids_tot 
      - pop_sud_plysbstnce_tot 
      - pop_sud_stmlnts_tot 
      - pop_sud_tbcco_tot 
      - pop_sud_other_tot 
    big_denom:
      - pop_sud_tot_base
    excel_order:
      - big_denom
      - count
      - pct

  t3:
    sas_ds: state_elgblty_grp_sud
    sheet_num: A.3.
    gen_wide: True
    group_cols: 
      - elgblty_grp_cat
    numer_col: pop_sud
    numer_value: ==1
    group_order: 
      - 1
      - 2
      - 3
      - 4
      - 5
      - 0
    big_denom:
      - pop_tot_base
    excel_order:
      - big_denom
      - denom
      - count
      - pct

  t4:
    sas_ds: state_elgblty_grp_sud
    sheet_num: A.4.
    gen_wide: True
    group_cols: 
      - elgblty_grp_cat
    numer_col: pop_sud
    numer_value: ==1
    group_order: 
      - 1
      - 2
      - 3
      - 4
      - 5
      - 0
    big_denom:
      - pop_sud_tot_base
    excel_order:
      - big_denom
      - count
      - pct

  t5:
    sas_ds: state_disabled2
    sas_ds_numer: state_disabled
    sheet_num: A.5.
    gen_wide: True
    group_cols: 
      - agecat
      - disabled_yr
    group_order: 
      - '1_0'
      - '1_1'
      - '2_0'
      - '2_1'
      - '3_0'
    big_denom:
      - pop_tot_base
    excel_order:
      - big_denom
      - denom
      - count
      - pct