# config for sud db tables

TABLE_MAPPINGS:

  t1:
    sas_ds: state_sud_methods
    sheet_num_sud: A.1.
    numerators: 
      - pop_sud_tot
      - pop_sud_alchl_tot 
      - pop_sud_cnnbs_tot 
      - pop_sud_opioids_tot 
      - pop_sud_plysbstnce_tot 
      - pop_sud_stmlnts_tot 
      - pop_sud_tbcco_tot 
      - pop_sud_other_tot 
    big_denom:
      - pop_tot_base
    excel_order:
      - big_denom
      - count
      - stat

  t2:
    sas_ds: state_sud_methods
    sheet_num_sud: A.2.
    numerators: 
      - pop_sud_alchl_tot 
      - pop_sud_cnnbs_tot 
      - pop_sud_opioids_tot 
      - pop_sud_plysbstnce_tot 
      - pop_sud_stmlnts_tot 
      - pop_sud_tbcco_tot 
      - pop_sud_other_tot 
    big_denom:
      - pop_sud_tot_base
    excel_order:
      - big_denom
      - count
      - stat

  t2_oud:
    sas_ds: state_sud_methods
    sheet_num_op: D.1.
    numerators: 
      - pop_sud_alchl_tot 
      - pop_sud_cnnbs_tot
      - pop_sud_plysbstnce_tot 
      - pop_sud_stmlnts_tot 
      - pop_sud_tbcco_tot 
      - pop_sud_other_tot 
    big_denom:
      - pop_sud_tot_base
    excel_order:
      - big_denom
      - count
      - stat

  t3:
    sas_ds: state_elgblty_grp_sud
    sheet_num_sud: A.3.
    use_class: TableClassWideTransform
    group_cols: 
      - elgblty_grp_cat
    denom: count
    numer: count
    numer_col: pop_sud
    numer_value: ==1
    group_order: 
      - 1
      - 2
      - 3
      - 4
      - 5
      - 0
    big_denom:
      - pop_tot_base
    excel_order:
      - big_denom
      - denom
      - count
      - stat

  t3_oud:
    sas_ds: state_elgblty_grp_sud
    sheet_num_op: D.3.
    use_class: TableClassWideTransform
    group_cols: 
      - elgblty_grp_cat
    denom: count
    numer: count
    numer_col: pop_sud
    numer_value: ==1
    group_order: 
      - 1
      - 2
      - 3
      - 4
      - 5
      - 0
    big_denom:
      - pop_tot_base
    excel_order:
      - big_denom
      - denom
      - count
      - stat

  t4:
    sas_ds: state_elgblty_grp_sud
    sheet_num_sud: A.4.
    use_class: TableClassWideTransform
    group_cols: 
      - elgblty_grp_cat
    denom: count
    numer: count
    numer_col: pop_sud
    numer_value: ==1
    suppress_second: True
    group_order: 
      - 1
      - 2
      - 3
      - 4
      - 5
      - 0
    big_denom:
      - pop_sud_tot_base
    excel_order:
      - big_denom
      - count
      - stat
    sheet_num_op: D.2.

  t5:
    sas_ds: state_disabled2
    sas_ds_numer: 
      - state_disabled
    sheet_num_sud: A.5.
    use_class: TableClassWideTransform
    group_cols: 
      - agecat
      - disabled_yr
    denom: count
    numer: count
    group_order: 
      - '1_0'
      - '1_1'
      - '2_0'
      - '2_1'
      - '3_0'
    big_denom:
      - pop_tot_base
    excel_order:
      - big_denom
      - denom
      - count
      - stat
    sheet_num_op: D.4.

  t6:
    sas_ds: state_disabled
    sheet_num_sud: A.6.
    use_class: TableClassWideTransform
    group_cols: 
      - agecat
      - disabled_yr
    numer: count
    suppress_second: True
    group_order: 
      - '1_0'
      - '1_1'
      - '2_0'
      - '2_1'
      - '3_0'
    big_denom:
      - pop_sud_tot_base
    excel_order:
      - big_denom
      - count
      - stat
    sheet_num_op: D.5.

  t7:
    sas_ds: state_duals2
    sheet_num_sud: A.7.
    use_class: TableClassDuals
    subset_col: full_dual
    subset_value: ==1
    numer_col: pop_sud
    numer_value: ==1
    count_cols: 
      - dual_count
      - dual_sud_count
    numerator: dual_sud_count
    denominators:
      - pop_sud_tot_base
      - dual_count
    big_denom:
      - pop_sud_tot_base

  t8:
    sas_ds: state_sud_set_srvc
    sheet_num_sud: B.2.
    use_class: TableClassCountsOnly
    count_cols: 
      - trt_srvc_case_mgmt 
      - trt_srvc_comm_sprt 
      - trt_srvc_cnsltn 
      - trt_srvc_cnsling 
      - trt_srvc_detox 
      - trt_srvc_emer_srvcs 
      - trt_srvc_inpat 
      - trt_srvc_intrvn 
      - trt_srvc_mat 
      - trt_srvc_med_mgmt
      - trt_srvc_obs_care 
      - trt_srvc_other 
      - trt_srvc_part_hosp 
      - trt_srvc_peer_sprt 
      - trt_srvc_phys_srvcs 
      - trt_srvc_rx 
      - trt_srvc_scn_assmt 
      - trt_srvc_treat
    sheet_num_op: D.6.

  t9:
    sas_ds: state_sud_set_srvc
    sheet_num_sud: C.1.
    numerators: 
      - trt_srvc_case_mgmt 
      - trt_srvc_comm_sprt 
      - trt_srvc_cnsltn 
      - trt_srvc_cnsling 
      - trt_srvc_detox 
      - trt_srvc_emer_srvcs 
      - trt_srvc_inpat 
      - trt_srvc_intrvn 
      - trt_srvc_mat 
      - trt_srvc_med_mgmt
      - trt_srvc_obs_care 
      - trt_srvc_other 
      - trt_srvc_part_hosp 
      - trt_srvc_peer_sprt 
      - trt_srvc_phys_srvcs 
      - trt_srvc_rx 
      - trt_srvc_scn_assmt 
      - trt_srvc_treat
    big_denom:
      - pop_sud_tot_base
    excel_order:
      - big_denom
      - count
      - stat
    sheet_num_op: D.7.

  t10:
    sas_ds: state_sud_set_srvc
    sheet_num_sud: C.2.
    numerators: 
      - inpatient
      - outpatient
      - residential
      - home
      - community
      - unknown
    big_denom:
      - pop_sud_tot_base
    excel_order:
      - big_denom
      - count
      - stat
    sheet_num_op: D.8.

  t11:
    sas_ds: state_sud_set_srvc
    sheet_num_sud: D.1.
    group_cols: []
    sas_ds_numer: 
      - stdy_inpat
      - stdy_mat
      - stdy_obs_care
      - stdy_part_hosp
      - stdy_treat
      - state_sud_count_claims
    numerators: 
      - tot_count_cnsltn 
      - tot_count_cnsling 
      - tot_count_emer_srvcs 
      - tot_count_inpat 
      - tot_count_mat 
      - tot_count_obs_care 
      - tot_count_part_hosp 
      - tot_count_phys_srvcs 
      - tot_count_scn_assmt 
      - tot_count_treat
    denominators: 
      - trt_srvc_cnsltn 
      - trt_srvc_cnsling 
      - trt_srvc_emer_srvcs 
      - trt_srvc_inpat 
      - trt_srvc_mat 
      - trt_srvc_obs_care 
      - trt_srvc_part_hosp 
      - trt_srvc_phys_srvcs 
      - trt_srvc_scn_assmt 
      - trt_srvc_treat
    big_denom:
      - pop_sud_tot_base
    prop_mult: 1
    excel_order:
      - big_denom
      - denom
      - count
      - stat
    sheet_num_op: D.9.

  t12:
    sas_ds: state_sud_methods
    sheet_num_sud: E.1.
    group_cols: []
    sas_ds_numer: 
      - state_sud_bene_mc
      - state_sud_bene_ffs
    numer_col_any:
      - claim_mc
      - claim_ffs
    numerators: 
      - claim_mc_count
      - claim_ffs_count
    big_denom:
      - pop_sud_tot
    excel_order:
      - big_denom
      - count
      - stat
    sheet_num_op: D.10.

  t13:
    sas_ds: state_sud_dates_30
    sheet_num_sud: F.1.
    numerators: 
      - any_service30
      - mult_service30
    big_denom:
      - nbenes
    excel_order:
      - big_denom
      - count
      - stat
    sheet_num_op: D.11.