# config for sud db tables

TABLE_MAPPINGS:
  t1:
    sas_ds: state_sud_methods
    sheet: A.1.
    numerators: 
      - pop_sud_alchl_tot 
      - pop_sud_cnnbs_tot 
      - pop_sud_opioids_tot 
      - pop_sud_plysbstnce_tot 
      - pop_sud_stmlnts_tot 
      - pop_sud_tbcco_tot 
      - pop_sud_other_tot 
    denominators:
      - pop_tot_base
    excel_order:
      - denominator
      - count
      - pct
    
    

